### ISSUE TITLE
Need Help. Sample data not getting ingested in docker - Self hosted installation. 

### ISSUE THREAD

**Issue by RVaidhy** [openobserve/openobserve#1324]
### Which OpenObserve functionalities are the source of the bug?

ingestion

### Is this a regression?

Yes

### Description

Hello Team,

I am trying to set up the open observe set up in a self hosted Docker mode and done with my installation too. The container is up and running. I am able to login to the portal too. while ingesting the data to the end point using the curl command I am receiving " curl: (52) Empty reply from server " this error. 

Even I have created a sample array of Json and tried to ingest the same with it.

The problem that I am facing is all theJson keys are getting ingested some how and NOT values. ( ie ) I could see all the columns and in the web UI with no values in it.

Please help me to resolve this. TIA.

Regards,
R Vaidyanathan

### Please provide the exception or error you saw

```true
curl: (52) Empty reply from server
```

### Anything else?

Since it contains our org sensitive details I am not be able to share any screenshot of it. Kindly excuse.

**Comment by RVaidhy** [comment]
Logs for your analysis.



[2023-08-03T14:06:05Z INFO  tracing::span] service:search:enter;
[2023-08-03T14:06:05Z INFO  tracing::span] service:search:cluster;
[2023-08-03T14:06:05Z INFO  tracing::span] service:search:sql:new;
[2023-08-03T14:06:05Z INFO  openobserve::service::search::sql] sqlparser: stream_name -> "default", fields -> [], partition_key -> [], full_text -> [], time_range -> Some((1691070665702000, 1691071565702000)), order_by -> [], limit -> 0,150
[2023-08-03T14:06:05Z INFO  tracing::span] get_file_list;
[2023-08-03T14:06:05Z INFO  openobserve::service::search] search->file_list: num: 0, offset: 1
[2023-08-03T14:06:05Z INFO  tracing::span] service:search:cluster:grpc_search;
[2023-08-03T14:06:05Z INFO  tracing::span] grpc:search:enter;
[2023-08-03T14:06:05Z INFO  tracing::span] service:search:grpc:search;
[2023-08-03T14:06:05Z INFO  tracing::span] service:search:sql:new;
[2023-08-03T14:06:05Z INFO  openobserve::service::search::sql] sqlparser: stream_name -> "default", fields -> [], partition_key -> [], full_text -> [], time_range -> Some((1691070665702000, 1691071565702000)), order_by -> [], limit -> 0,150
[2023-08-03T14:06:05Z INFO  tracing::span] service:search:grpc:in_wal;
[2023-08-03T14:06:05Z INFO  tracing::span] service:search:grpc:in_storage;
[2023-08-03T14:06:05Z INFO  tracing::span] service:search:wal:enter;
[2023-08-03T14:06:05Z INFO  tracing::span] service:search:grpc:wal:get_file_list;
[2023-08-03T14:06:05Z INFO  openobserve::service::search] search->grpc: result node: 1, is_querier: true, total: 0, took: 2, files: 0, scan_size: 0
[2023-08-03T14:06:05Z INFO  openobserve::service::search] search->result: total: 0, took: 3, scan_size: 0
[2023-08-03T14:06:05Z INFO  actix_web::middleware::logger] 10.76.65.190 "POST /api/default/_search?type=logs HTTP/1.1" 200 120 "278" "http://144.70.96.76:5080/web/logs?org_identifier=default" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36" 0.005307
[2023-08-03T14:06:15Z ERROR openobserve::job::metrics] Error update metadata metrics: SledError# IO error: No such file or directory (os error 2)
[2023-08-03T14:06:45Z ERROR openobserve::job::metrics] Error update metadata metrics: SledError# IO error: No such file or directory (os error 2)
[2023-08-03T14:06:45Z INFO  openobserve::service::compact::file_list] [COMPACT] file_list is waiting for stream: default/logs/default, offset: 1691067600000000
[2023-08-03T14:07:15Z ERROR openobserve::job::metrics] Error update metadata metrics: SledError# IO error: No such file or directory (os error 2)
[2023-08-03T14:07:45Z ERROR openobserve::job::metrics] Error update metadata metrics: SledError# IO error: No such file or directory (os error 2)
[2023-08-03T14:07:45Z INFO  openobserve::service::compact::file_list] [COMPACT] file_list is waiting for stream: default/logs/default, offset: 1691067600000000
[2023-08-03T14:08:15Z ERROR openobserve::job::metrics] Error update metadata metrics: SledError# IO error: No such file or directory (os error 2)
[2023-08-03T14:08:45Z ERROR openobserve::job::metrics] Error update metadata metrics: SledError# IO error: No such file or directory (os error 2)
[2023-08-03T14:08:45Z INFO  openobserve::service::compact::file_list] [COMPACT] file_list is waiting for stream: default/logs/default, offset: 1691067600000000
[2023-08-03T14:09:15Z ERROR openobserve::job::metrics] Error update metadata metrics: SledError# IO error: No such file or directory (os error 2)
[2023-08-03T14:09:45Z ERROR openobserve::job::metrics] Error update metadata metrics: SledError# IO error: No such file or directory (os error 2)
[2023-08-03T14:09:45Z INFO  openobserve::service::compact::file_list] [COMPACT] file_list is waiting for stream: default/logs/default, offset: 1691067600000000
[2023-08-03T14:10:15Z ERROR openobserve::job::metrics] Error update metadata metrics: SledError# IO error: No such file or directory (os error 2)
[2023-08-03T14:10:45Z ERROR openobserve::job::metrics] Error update metadata metrics: SledError# IO error: No such file or directory (os error 2)
[2023-08-03T14:10:45Z INFO  openobserve::service::compact::file_list] [COMPACT] file_list is waiting for stream: default/logs/default, offset: 1691067600000000
[2023-08-03T14:11:15Z ERROR openobserve::job::metrics] Error update metadata metrics: SledError# IO error: No such file or directory (os error 2)
[2023-08-03T14:11:45Z ERROR openobserve::job::metrics] Error update metadata metrics: SledError# IO error: No such file or directory (os error 2)
[2023-08-03T14:11:45Z INFO  openobserve::service::compact::file_list] [COMPACT] file_list is waiting for stream: default/logs/default, offset: 1691067600000000
[2023-08-03T14:12:15Z ERROR openobserve::job::metrics] Error update metadata metrics: SledError# IO error: No such file or directory (os error 2)
[2023-08-03T14:12:45Z ERROR openobserve::job::metrics] Error update metadata metrics: SledError# IO error: No such file or directory (os error 2)
[2023-08-03T14:12:45Z INFO  openobserve::service::compact::file_list] [COMPACT] file_list is waiting for stream: default/logs/default, offset: 1691067600000000
[2023-08-03T14:13:15Z ERROR openobserve::job::metrics] Error update metadata metrics: SledError# IO error: No such file or directory (os error 2)
[2023-08-03T14:13:45Z ERROR openobserve::job::metrics] Error update metadata metrics: SledError# IO error: No such file or directory (os error 2)
[2023-08-03T14:13:45Z INFO  openobserve::service::compact::file_list] [COMPACT] file_list is waiting for stream: default/logs/default, offset: 1691067600000000
[2023-08-03T14:14:15Z ERROR openobserve::job::metrics] Error update metadata metrics: SledError# IO error: No such file or directory (os error 2)
[2023-08-03T14:14:45Z ERROR openobserve::job::metrics] Error update metadata metrics: SledError# IO error: No such file or directory (os error 2)
[2023-08-03T14:14:45Z INFO  openobserve::service::compact::file_list] [COMPACT] file_list is waiting for stream: default/logs/default, offset: 1691067600000000
[2023-08-03T14:15:15Z ERROR openobserve::job::metrics] Error update metadata metrics: SledError# IO error: No such file or directory (os error 2)
[2023-08-03T14:15:45Z ERROR openobserve::job::metrics] Error update metadata metrics: SledError# IO error: No such file or directory (os error 2)
[2023-08-03T14:15:45Z INFO  openobserve::service::compact::file_list] [COMPACT] file_list is waiting for stream: default/logs/default, offset: 1691067600000000
[2023-08-03T14:16:15Z ERROR openobserve::job::metrics] Error update metadata metrics: SledError# IO error: No such file or directory (os error 2)
[2023-08-03T14:16:45Z ERROR openobserve::job::metrics] Error update metadata metrics: SledError# IO error: No such file or directory (os error 2)
[2023-08-03T14:16:45Z INFO  openobserve::service::compact::file_list] [COMPACT] file_list is waiting for stream: default/logs/default, offset: 1691067600000000
[2023-08-03T14:17:15Z ERROR openobserve::job::metrics] Error update metadata metrics: SledError# IO error: No such file or directory (os error 2)
[2023-08-03T14:17:45Z ERROR openobserve::job::metrics] Error update metadata metrics: SledError# IO error: No such file or directory (os error 2)
[2023-08-03T14:17:45Z INFO  openobserve::service::compact::file_list] [COMPACT] file_list is waiting for stream: default/logs/default, offset: 1691067600000000
[2023-08-03T14:18:15Z ERROR openobserve::job::metrics] Error update metadata metrics: SledError# IO error: No such file or directory (os error 2)
[2023-08-03T14:18:45Z INFO  openobserve::common::meta::telemetry] sending event OpenObserve - heartbeat
[2023-08-03T14:18:45Z ERROR openobserve::job::metrics] Error update metadata metrics: SledError# IO error: No such file or directory (os error 2)
[2023-08-03T14:18:45Z INFO  openobserve::service::compact::file_list] [COMPACT] file_list is waiting for stream: default/logs/default, offset: 1691067600000000
[2023-08-03T14:18:55Z ERROR openobserve::common::meta::telemetry] Error sending event OpenObserve - heartbeat, Err(NetworkError(reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("e1.zinclabs.dev")), port: None, path: "/v1/track", query: None, fragment: None }, source: hyper::Error(Connect, TimedOut) }))
[2023-08-03T14:19:15Z ERROR openobserve::job::metrics] Error update metadata metrics: SledError# IO error: No such file or directory (os error 2)
[2023-08-03T14:19:45Z ERROR openobserve::job::metrics] Error update metadata metrics: SledError# IO error: No such file or directory (os error 2)
[2023-08-03T14:19:45Z INFO  openobserve::service::compact::file_list] [COMPACT] file_list is waiting for stream: default/logs/default, offset: 1691067600000000
[2023-08-03T14:20:15Z ERROR openobserve::job::metrics] Error update metadata metrics: SledError# IO error: No such file or directory (os error 2)
[2023-08-03T14:20:45Z ERROR openobserve::job::metrics] Error update metadata metrics: SledError# IO error: No such file or directory (os error 2)
[2023-08-03T14:20:45Z INFO  openobserve::service::compact::file_list] [COMPACT] file_list is waiting for stream: default/logs/default, offset: 1691067600000000
[2023-08-03T14:20:55Z INFO  openobserve::service::schema] Acquired lock for stream default as schema is empty
[2023-08-03T14:20:55Z INFO  openobserve::service::schema] Setting schema for stream default as schema is empty
[2023-08-03T14:20:55Z INFO  openobserve::service::schema] Acquired lock for stream default to update schema
[2023-08-03T14:20:55Z INFO  openobserve::service::schema] Acquired lock for stream default to update schema
[2023-08-03T14:20:55Z INFO  openobserve::service::schema] Acquired lock for stream default to update schema
thread 'actix-server worker 3' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/common/infra/wal.rs:312:44
[2023-08-03T14:21:15Z ERROR openobserve::job::metrics] Error update metadata metrics: SledError# IO error: No such file or directory (os error 2)
thread 'actix-server worker 0' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/common/infra/wal.rs:312:44
[2023-08-03T14:21:45Z ERROR openobserve::job::metrics] Error update metadata metrics: SledError# IO error: No such file or directory (os error 2)
[2023-08-03T14:21:45Z INFO  openobserve::service::compact::file_list] [COMPACT] file_list is waiting for stream: default/logs/default, offset: 1691067600000000
[2023-08-03T14:22:15Z ERROR openobserve::job::metrics] Error update metadata metrics: SledError# IO error: No such file or directory (os error 2)

**Comment by hengfeiyang** [comment]
```
 No such file or directory (os error 2)
```

How do you configure your docker, it looks need mount a `/data` directory and give it privilege, like `777`

**Comment by RVaidhy** [comment]
Hello hengfeiyang, 

Thanks for the reply.

1. I have created the container using the below steps as mentioned in the document.

---> mkdir data
---> docker run -v $PWD/data:/data -e ZO_DATA_DIR="/data" -p 5080:5080 \
    -e ZO_ROOT_USER_EMAIL="root@example.com" -e ZO_ROOT_USER_PASSWORD="Complexpass#123" \
    public.ecr.aws/zinclabs/openobserve:latest


2. Also I have changed the permission to 777 for the /data folder.
---> 
drwxr-xr-x   14 root root   4096 Aug  3 07:15 root
drwxrwxrwx    2 root root    122 Aug  3 10:21 data
drwxr-xr-x   38 root root   1380 Aug  4 02:03 run
drwxrwxrwt.  79 root root   4096 Aug  4 03:18 tmp

Please check the above details. 

I am unable to login to the container by using the below exec command. It throws the following error.

-------------------
root@xx.xx.xx.xx:/ #  **docker exec -it bce69f7eea57 sh**
OCI runtime exec failed: exec failed: unable to start container process: exec: "sh": executable file not found in $PATH: unknown
root@xx.xx.xx.xx:/ # **docker exec -it bce69f7eea57 /openobserve**
[2023-08-04T07:42:38Z INFO  openobserve] Starting OpenObserve v0.5.1
thread 'tokio-runtime-worker' panicked at 'sled db dir create failed: Io(Os { code: 2, kind: NotFound, message: "No such file or directory" })', src/common/infra/db/sled.rs:309:50
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: channel closed


The curl I am using is as follows,

curl -u root@example.com:<<password_from_the_portal>> -k http://xx.xx.xx.xx:5080/api/default/default/_json -d "@k8slog_json.json"
curl: (52) Empty reply from server


Am I doing anything wrong here ?  Why the array of Json data ([ "KEY1":"Value1"]) keys alone got ingested and not data (Values) in the web portal. I can see the columns alone.

Please help me to resolve this issue. 

Thanks,
R Vaidyanathan

**Comment by hengfeiyang** [comment]
Sorry for late reply you.

First I saw you created `/data` directory. but you give the container `$PWD/data`, is this the same directory?

Try this:

```
docker run -v $PWD/data:/data -e ZO_DATA_DIR="/data" -p 5080:5080 \
  -e ZO_ROOT_USER_EMAIL="[root@example.com](mailto:root@example.com)" \
  -e ZO_ROOT_USER_PASSWORD="Complexpass#123" \
  public.ecr.aws/zinclabs/openobserve:latest
```

If you want to enter the container, you can use this tag:

```
public.ecr.aws/zinclabs/openobserve:v0.5.1-debug
```
