### ISSUE TITLE
assertion failed: datatype.is_primitive() - When using the VRL functions.

### ISSUE THREAD

**Issue by gcarrarom** [openobserve/openobserve#2380]
### Which OpenObserve functionalities are the source of the bug?

functions

### Is this a regression?

Yes

### Description

My system now can't use VRL functions to do any queries or ingestion changes. Every time I try to use any VRL function to query/stream ingest, it now throws the following on the logs: 
```
openobserve/openobserve-querier-6985f995b7-hf6tb[openobserve]: thread 'tokio-runtime-worker' panicked at /usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/b648d4e/datafusion/common/src/scalar.rs:760:9:
openobserve/openobserve-querier-6985f995b7-hf6tb[openobserve]: assertion failed: datatype.is_primitive()
openobserve/openobserve-querier-6985f995b7-hf6tb[openobserve]: [2024-01-03T15:58:09Z ERROR openobserve::service::search] [session_id 88780026-d26a-4d53-bf44-426169c917e7] search->grpc: node: http://10.42.4.214:5081, search err: Status { code: Internal, message: "{\"code\":10001,\"inner\":\"task 60391 panicked\",\"message\":\"Server Internal Error\"}", metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Wed, 03 Jan 2024 15:58:09 GMT", "content-length": "0"} }, source: None }
openobserve/openobserve-querier-6985f995b7-hf6tb[openobserve]: [2024-01-03T15:58:09Z ERROR openobserve::service::search] [session_id 88780026-d26a-4d53-bf44-426169c917e7] search->grpc: node: http://10.42.4.217:50810, search err: Status { code: Internal, message: "{\"code\":10001,\"inner\":\"task 39583 panicked\",\"message\":\"Server Internal Error\"}", metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Wed, 03 Jan 2024 15:58:09 GMT", "content-length": "0"} }, source: None }
openobserve/openobserve-querier-6985f995b7-hf6tb[openobserve]: [2024-01-03T15:58:09Z ERROR openobserve::handler::http::request::search] search error: ErrorCode(ServerInternalError("task 39583 panicked"))
openobserve/openobserve-querier-6985f995b7-hf6tb[openobserve]: [2024-01-03T15:58:09Z INFO  actix_web::middleware::logger] 10.42.4.212 "POST /api/default/_search?type=logs HTTP/1.1" 500 100 "-" "https://observe.fancywhale.ca/web/logs?stream=default&period=15m&refresh=0&org_identifier=default&timezone=America/Toronto" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:121.0) Gecko/20100101 Firefox/121.0" 0.407748
openobserve/openobserve-querier-6985f995b7-hf6tb[openobserve]: [2024-01-03T15:58:18Z INFO  openobserve::service::search] service:search:enter; session_id="19a0f27e-af63-4688-a5a7-778651fe2814" org_id="default" stream_type=Logs
openobserve/openobserve-querier-6985f995b7-hf6tb[openobserve]: [2024-01-03T15:58:18Z INFO  openobserve::service::search] service:search:cluster; session_id="19a0f27e-af63-4688-a5a7-778651fe2814" org_id="default"
openobserve/openobserve-querier-6985f995b7-hf6tb[openobserve]: [2024-01-03T15:58:18Z INFO  openobserve::service::search] get_file_list; _session_id="19a0f27e-af63-4688-a5a7-778651fe2814" stream_type=Logs time_level=Hourly session_id="19a0f27e-af63-4688-a5a7-778651fe2814" org_id="default" stream_name="default"
openobserve/openobserve-querier-6985f995b7-hf6tb[openobserve]: [2024-01-03T15:58:18Z INFO  openobserve::service::search] [session_id 19a0f27e-af63-4688-a5a7-778651fe2814] search->file_list: time_range: Some((1704296598016000, 1704297498016000)), num: 3, offset: 4
openobserve/openobserve-querier-6985f995b7-hf6tb[openobserve]: [2024-01-03T15:58:18Z INFO  openobserve::service::search] service:search:cluster:grpc_search; session_id="19a0f27e-af63-4688-a5a7-778651fe2814" org_id="default"
openobserve/openobserve-querier-6985f995b7-hf6tb[openobserve]: [2024-01-03T15:58:18Z INFO  openobserve::service::search] service:search:cluster:grpc_search; session_id="19a0f27e-af63-4688-a5a7-778651fe2814" org_id="default"
openobserve/openobserve-querier-6985f995b7-hf6tb[openobserve]: [2024-01-03T15:58:18Z INFO  openobserve::handler::grpc::request::search] grpc:search:enter; session_id="19a0f27e-af63-4688-a5a7-778651fe2814" org_id="default"
openobserve/openobserve-querier-6985f995b7-hf6tb[openobserve]: [2024-01-03T15:58:18Z INFO  openobserve::service::search::grpc] service:search:grpc:search; session_id="19a0f27e-af63-4688-a5a7-778651fe2814" org_id="default"
openobserve/openobserve-querier-6985f995b7-hf6tb[openobserve]: [2024-01-03T15:58:18Z INFO  openobserve::service::search::grpc] service:search:grpc:in_wal; session_id="19a0f27e-af63-4688-a5a7-778651fe2814" org_id="default" stream_name="default" stream_type=Logs
openobserve/openobserve-querier-6985f995b7-hf6tb[openobserve]: [2024-01-03T15:58:18Z INFO  openobserve::service::search::grpc] service:search:grpc:in_storage; session_id="19a0f27e-af63-4688-a5a7-778651fe2814" org_id="default" stream_name="default" stream_type=Logs
openobserve/openobserve-querier-6985f995b7-hf6tb[openobserve]: [2024-01-03T15:58:18Z INFO  openobserve::service::search::grpc::storage] service:search:grpc:storage:enter; session_id="19a0f27e-af63-4688-a5a7-778651fe2814" org_id="default" stream_name="default"
openobserve/openobserve-querier-6985f995b7-hf6tb[openobserve]: [2024-01-03T15:58:18Z INFO  openobserve::service::search::grpc::storage] [session_id 19a0f27e-af63-4688-a5a7-778651fe2814] search->storage: org default, stream default, load file_list num 3
openobserve/openobserve-querier-6985f995b7-hf6tb[openobserve]: [2024-01-03T15:58:18Z INFO  openobserve::service::search::grpc::storage] [session_id 19a0f27e-af63-4688-a5a7-778651fe2814] search->storage: org default, stream default, load files 3, scan_size 101224150, compressed_size 2141336
openobserve/openobserve-querier-6985f995b7-hf6tb[openobserve]: [2024-01-03T15:58:18Z INFO  openobserve::service::search::grpc::storage] service:search:grpc:storage:cache_parquet_files; session_id="19a0f27e-af63-4688-a5a7-778651fe2814"
openobserve/openobserve-querier-6985f995b7-hf6tb[openobserve]: [2024-01-03T15:58:18Z INFO  openobserve::service::search::grpc::storage] [session_id 19a0f27e-af63-4688-a5a7-778651fe2814] search->storage: org default, stream default, load files 3, into Memory cache done
openobserve/openobserve-querier-6985f995b7-hf6tb[openobserve]: [2024-01-03T15:58:18Z INFO  openobserve::service::search::grpc::storage] service:search:grpc:storage:datafusion; session_id="19a0f27e-af63-4688-a5a7-778651fe2814" org_id="default" stream_name="default" stream_type=Logs
openobserve/openobserve-querier-6985f995b7-hf6tb[openobserve]: [2024-01-03T15:58:18Z INFO  tracing::span] datafusion::storage::memory::list;
openobserve/openobserve-querier-6985f995b7-hf6tb[openobserve]: thread 'tokio-runtime-worker' panicked at /usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/b648d4e/datafusion/common/src/scalar.rs:760:9:
openobserve/openobserve-querier-6985f995b7-hf6tb[openobserve]: assertion failed: datatype.is_primitive()
openobserve/openobserve-querier-6985f995b7-hf6tb[openobserve]: [2024-01-03T15:58:18Z ERROR openobserve::service::search] [session_id 19a0f27e-af63-4688-a5a7-778651fe2814] search->grpc: node: http://10.42.4.214:5081, search err: Status { code: Internal, message: "{\"code\":10001,\"inner\":\"task 60426 panicked\",\"message\":\"Server Internal Error\"}", metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Wed, 03 Jan 2024 15:58:18 GMT", "content-length": "0"} }, source: None }
```

### Please provide the exception or error you saw

```true
openobserve/openobserve-querier-6985f995b7-hf6tb[openobserve]: thread 'tokio-runtime-worker' panicked at /usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/b648d4e/datafusion/common/src/scalar.rs:760:9:
openobserve/openobserve-querier-6985f995b7-hf6tb[openobserve]: assertion failed: datatype.is_primitive()
openobserve/openobserve-querier-6985f995b7-hf6tb[openobserve]: [2024-01-03T15:58:09Z ERROR openobserve::service::search] [session_id 88780026-d26a-4d53-bf44-426169c917e7] search->grpc: node: http://10.42.4.214:5081, search err: Status { code: Internal, message: "{\"code\":10001,\"inner\":\"task 60391 panicked\",\"message\":\"Server Internal Error\"}", metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Wed, 03 Jan 2024 15:58:09 GMT", "content-length": "0"} }, source: None }
openobserve/openobserve-querier-6985f995b7-hf6tb[openobserve]: [2024-01-03T15:58:09Z ERROR openobserve::service::search] [session_id 88780026-d26a-4d53-bf44-426169c917e7] search->grpc: node: http://10.42.4.217:50810, search err: Status { code: Internal, message: "{\"code\":10001,\"inner\":\"task 39583 panicked\",\"message\":\"Server Internal Error\"}", metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Wed, 03 Jan 2024 15:58:09 GMT", "content-length": "0"} }, source: None }
openobserve/openobserve-querier-6985f995b7-hf6tb[openobserve]: [2024-01-03T15:58:09Z ERROR openobserve::handler::http::request::search] search error: ErrorCode(ServerInternalError("task 39583 panicked"))
openobserve/openobserve-querier-6985f995b7-hf6tb[openobserve]: [2024-01-03T15:58:09Z INFO  actix_web::middleware::logger] 10.42.4.212 "POST /api/default/_search?type=logs HTTP/1.1" 500 100 "-" "https://observe.fancywhale.ca/web/logs?stream=default&period=15m&refresh=0&org_identifier=default&timezone=America/Toronto" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:121.0) Gecko/20100101 Firefox/121.0" 0.407748
openobserve/openobserve-querier-6985f995b7-hf6tb[openobserve]: [2024-01-03T15:58:18Z INFO  openobserve::service::search] service:search:enter; session_id="19a0f27e-af63-4688-a5a7-778651fe2814" org_id="default" stream_type=Logs
openobserve/openobserve-querier-6985f995b7-hf6tb[openobserve]: [2024-01-03T15:58:18Z INFO  openobserve::service::search] service:search:cluster; session_id="19a0f27e-af63-4688-a5a7-778651fe2814" org_id="default"
openobserve/openobserve-querier-6985f995b7-hf6tb[openobserve]: [2024-01-03T15:58:18Z INFO  openobserve::service::search] get_file_list; _session_id="19a0f27e-af63-4688-a5a7-778651fe2814" stream_type=Logs time_level=Hourly session_id="19a0f27e-af63-4688-a5a7-778651fe2814" org_id="default" stream_name="default"
openobserve/openobserve-querier-6985f995b7-hf6tb[openobserve]: [2024-01-03T15:58:18Z INFO  openobserve::service::search] [session_id 19a0f27e-af63-4688-a5a7-778651fe2814] search->file_list: time_range: Some((1704296598016000, 1704297498016000)), num: 3, offset: 4
openobserve/openobserve-querier-6985f995b7-hf6tb[openobserve]: [2024-01-03T15:58:18Z INFO  openobserve::service::search] service:search:cluster:grpc_search; session_id="19a0f27e-af63-4688-a5a7-778651fe2814" org_id="default"
openobserve/openobserve-querier-6985f995b7-hf6tb[openobserve]: [2024-01-03T15:58:18Z INFO  openobserve::service::search] service:search:cluster:grpc_search; session_id="19a0f27e-af63-4688-a5a7-778651fe2814" org_id="default"
openobserve/openobserve-querier-6985f995b7-hf6tb[openobserve]: [2024-01-03T15:58:18Z INFO  openobserve::handler::grpc::request::search] grpc:search:enter; session_id="19a0f27e-af63-4688-a5a7-778651fe2814" org_id="default"
openobserve/openobserve-querier-6985f995b7-hf6tb[openobserve]: [2024-01-03T15:58:18Z INFO  openobserve::service::search::grpc] service:search:grpc:search; session_id="19a0f27e-af63-4688-a5a7-778651fe2814" org_id="default"
openobserve/openobserve-querier-6985f995b7-hf6tb[openobserve]: [2024-01-03T15:58:18Z INFO  openobserve::service::search::grpc] service:search:grpc:in_wal; session_id="19a0f27e-af63-4688-a5a7-778651fe2814" org_id="default" stream_name="default" stream_type=Logs
openobserve/openobserve-querier-6985f995b7-hf6tb[openobserve]: [2024-01-03T15:58:18Z INFO  openobserve::service::search::grpc] service:search:grpc:in_storage; session_id="19a0f27e-af63-4688-a5a7-778651fe2814" org_id="default" stream_name="default" stream_type=Logs
openobserve/openobserve-querier-6985f995b7-hf6tb[openobserve]: [2024-01-03T15:58:18Z INFO  openobserve::service::search::grpc::storage] service:search:grpc:storage:enter; session_id="19a0f27e-af63-4688-a5a7-778651fe2814" org_id="default" stream_name="default"
openobserve/openobserve-querier-6985f995b7-hf6tb[openobserve]: [2024-01-03T15:58:18Z INFO  openobserve::service::search::grpc::storage] [session_id 19a0f27e-af63-4688-a5a7-778651fe2814] search->storage: org default, stream default, load file_list num 3
openobserve/openobserve-querier-6985f995b7-hf6tb[openobserve]: [2024-01-03T15:58:18Z INFO  openobserve::service::search::grpc::storage] [session_id 19a0f27e-af63-4688-a5a7-778651fe2814] search->storage: org default, stream default, load files 3, scan_size 101224150, compressed_size 2141336
openobserve/openobserve-querier-6985f995b7-hf6tb[openobserve]: [2024-01-03T15:58:18Z INFO  openobserve::service::search::grpc::storage] service:search:grpc:storage:cache_parquet_files; session_id="19a0f27e-af63-4688-a5a7-778651fe2814"
openobserve/openobserve-querier-6985f995b7-hf6tb[openobserve]: [2024-01-03T15:58:18Z INFO  openobserve::service::search::grpc::storage] [session_id 19a0f27e-af63-4688-a5a7-778651fe2814] search->storage: org default, stream default, load files 3, into Memory cache done
openobserve/openobserve-querier-6985f995b7-hf6tb[openobserve]: [2024-01-03T15:58:18Z INFO  openobserve::service::search::grpc::storage] service:search:grpc:storage:datafusion; session_id="19a0f27e-af63-4688-a5a7-778651fe2814" org_id="default" stream_name="default" stream_type=Logs
openobserve/openobserve-querier-6985f995b7-hf6tb[openobserve]: [2024-01-03T15:58:18Z INFO  tracing::span] datafusion::storage::memory::list;
openobserve/openobserve-querier-6985f995b7-hf6tb[openobserve]: thread 'tokio-runtime-worker' panicked at /usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/b648d4e/datafusion/common/src/scalar.rs:760:9:
openobserve/openobserve-querier-6985f995b7-hf6tb[openobserve]: assertion failed: datatype.is_primitive()
openobserve/openobserve-querier-6985f995b7-hf6tb[openobserve]: [2024-01-03T15:58:18Z ERROR openobserve::service::search] [session_id 19a0f27e-af63-4688-a5a7-778651fe2814] search->grpc: node: http://10.42.4.214:5081, search err: Status { code: Internal, message: "{\"code\":10001,\"inner\":\"task 60426 panicked\",\"message\":\"Server Internal Error\"}", metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Wed, 03 Jan 2024 15:58:18 GMT", "content-length": "0"} }, source: None }
```

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: v0.7.2
Commit Hash: c6e7b19b28e948cfc65e4dfb3d26a0cfebbec3f8
Build Date: 2023-11-30T07:59:17Z
OS: Linux 64
```

### Anything else?

I've tried to single out what could be generating this error. So I've made a query that is just one record:
![CleanShot 2024-01-03 at 11 03 27](https://github.com/openobserve/openobserve/assets/10549675/74f3dfda-af97-4d4d-ad4b-45cc31429728)
Then tried adding a new piece to the record with a function like so:
```vrl
.try="something"
```
Which results in the assertion failed: datatype.is_primitive() error:
![CleanShot 2024-01-03 at 11 04 35](https://github.com/openobserve/openobserve/assets/10549675/fd21f834-9687-48fe-b143-3c4b1acf1fae)

**Comment by prabhatsharma** [comment]
@gcarrarom Is it possible for you to provide a sample data set where it occurs, which will help us reproduce this.

**Comment by gcarrarom** [comment]
Here:
https://fncy.ca/7yDU4

**Comment by prabhatsharma** [comment]
This data works perfectly well. You might have more records than this one of which is causing the issue.

[martins.json](https://github.com/openobserve/openobserve/files/13822986/martins.json)

**Comment by gcarrarom** [comment]
I guess I'm not sure then. When running the VRL functions on the log query page, does it run the function after the filter or before? If it is before, then I might need to clean up the data a bit, if it is after, then this is all that is found on that query.

**Comment by prabhatsharma** [comment]
Currently, VRL filters more than what you get the results on the UI. In the upcoming release, that will change, and VRL function will be applied only to the results on the UI. This should help get rid of the error for most scenarios. If there are errors, it will become easier to isolate and fix them.

**Comment by gcarrarom** [comment]
Would it be possible to enable some sort of debug option to grab the entry that might be running into this assertion issue?

**Comment by prabhatsharma** [comment]
@oasisk Thoughts ?

**Comment by gcarrarom** [comment]
Not sure what happened in between, but I've upgraded my OpenObserve deployment and the error is gone. I'll observe and report back if the issue arises again. But I'd still like to know if there's a way to check which record would introduce issues to my functions/ingestion.
