### ISSUE TITLE
OpenObserve and pino

### ISSUE THREAD

**Issue by YChebotaev** [openobserve/openobserve#2408]
### Which OpenObserve functionalities are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

I need to log to OpenSearch from pino

My config is:

```typescript
import pino from "pino";
import pinoElasticsearch from "pino-elasticsearch";
import { multistream } from "pino-multi-stream";

const username = process.env["OPENOBSERVE_USERNAME"];
const password = process.env["OPENOBSERVE_PASSWORD"];

if (!username || !password) {
  console.error(
    "Both OPENOBSERVE_USERNAME and OPENOBSERVE_PASSWORD environment variables must be set",
  );

  process.exit(1);
}

export const createLogger = (index: string) => {
  const streamToOpenObserve = pinoElasticsearch({
    index,
    node: "http://localhost:5080/api/default/",
    esVersion: 7,
    flushBytes: 1000,
    auth: {
      username,
      password,
    },
  });

  return pino(
    { level: "info" },
    multistream([
      { stream: streamToOpenObserve },
      { stream: process.stdout, level: "info" },
      { stream: process.stderr, level: "error" },
    ]),
  );
};
```

I followed [this](https://openobserve.ai/blog/how-to-send-pino-logs-to-openobserve/) tutorial, but it's not working

Error says that url is invalid

### Please provide the exception or error you saw

```true
/Users/ychebotaev/Projects/checkyourstaff/node_modules/undici/lib/core/util.js:117
    throw new InvalidArgumentError('invalid url')
          ^
InvalidArgumentError: invalid url
    at Object.parseOrigin (/Users/ychebotaev/Projects/checkyourstaff/node_modules/undici/lib/core/util.js:117:11)
    at new Pool (/Users/ychebotaev/Projects/checkyourstaff/node_modules/undici/lib/pool.js:70:23)
    at new Connection (/Users/ychebotaev/Projects/checkyourstaff/node_modules/@elastic/transport/src/connection/UndiciConnection.ts:113:17)
    at WeightedConnectionPool.createConnection (/Users/ychebotaev/Projects/checkyourstaff/node_modules/@elastic/transport/src/pool/BaseConnectionPool.ts:133:24)
    at WeightedConnectionPool.addConnection (/Users/ychebotaev/Projects/checkyourstaff/node_modules/@elastic/transport/src/pool/BaseConnectionPool.ts:158:53)
    at new Client (/Users/ychebotaev/Projects/checkyourstaff/node_modules/@elastic/elasticsearch/src/client.ts:240:27)
    at pinoElasticSearch (/Users/ychebotaev/Projects/checkyourstaff/node_modules/pino-elasticsearch/lib.js:141:18)
    at createLogger (/Users/ychebotaev/Projects/checkyourstaff/common/createLogger.ts:17:48)
    at Object.<anonymous> (/Users/ychebotaev/Projects/checkyourstaff/persistence/logger.ts:3:35)
    at Module._compile (node:internal/modules/cjs/loader:1099:14) {
  code: 'UND_ERR_INVALID_ARG'
}
```

### Please provide the version you discovered this bug in (check about page for version information)

```true
v0.7.2
c6e7b19b28e948cfc65e4dfb3d26a0cfebbec3f8
2023-11-30T07:59:17Z
OS: Macos 10.13.6
```

**Comment by YChebotaev** [comment]
@oasisk Any progress on this?

**Comment by ktx-kirtan** [comment]
@YChebotaev  We have created our own npm library for sending pino logs to OpenObserve. Please check details on our blog post:  https://openobserve.ai/blog/sending-pino-logs-to-openobserve

**Comment by YChebotaev** [comment]
@ktx-kirtan Thanks. But typings would nice to have. For not it's errored from TS:
```
error TS7016: Could not find a declaration file for module '@openobserve/pino-openobserve'. '/Users/ychebotaev/Projects/checkyourstaff/node_modules/@openobserve/pino-openobserve/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/openobserve__pino-openobserve` if it exists or add a new declaration (.d.ts) file containing `declare module '@openobserve/pino-openobserve';`
```

**Comment by ktx-kirtan** [comment]
Thanks. Yes, will add those in the next version
