### ISSUE TITLE
OTLP http -json - Logs not being ingested

### ISSUE THREAD

**Issue by cocowalla** [openobserve/openobserve#2532]
### Which OpenObserve functionalities are the source of the bug?

ingestion

### Is this a regression?

No

### Description

I'm evaluating OpenObserve, and trace and metrics functions are working as expected, but logs are not being ingested at all.

To reproduce:

```bash
curl --request POST "http://localhost:5080/api/default/v1/logs" \
	-H "Content-Type: application/json" \
	-H "Authorization: Basic <MY BASE64 CREDENTIALS HERE>" \
	--data '{"resource_logs":[{"resource":{"attributes":[{"key":"service.name","value":{"stringValue":"test-with-curl"}}]},"scope_logs":[{"scope":{"name":"manual-test"},"log_records":[{"time_unix_nano":"1705922660000000000","observed_time_unix_nano":"1705922660000000000","name":"test","severity_text":"INFO"}]}]}]}'
```

I see this error:

```
thread 'actix-server worker 1' panicked at src/service/logs/otlp_http.rs:291:40:
called `Option::unwrap()` on a `None` value
```

### Please provide a link to a minimal reproduction of the bug

Please see description

### Please provide the exception or error you saw

```true
thread 'actix-server worker 1' panicked at src/service/logs/otlp_http.rs:291:40:
called `Option::unwrap()` on a `None` value
```
```


### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: v0.8.0-rc1
Commit Hash: c057bf40f34206914e17b623c6bc31e4ad8f17c7
Build Date: 2024-01-16T13:21:57Z
OS: linux x64 (Docker)
```

**Comment by cocowalla** [comment]
Seems it won't ingest JSON logs if the Span ID and/or Trace ID are missing. AFAICT it does work with HTTP protobufs though.

**Comment by oasisk** [comment]
fixed by : https://github.com/openobserve/openobserve/pull/2546
