### ISSUE TITLE
Traces ingestion panicked at src/service/traces/mod.rs:209 

### ISSUE THREAD

**Issue by hengfeiyang** [openobserve/openobserve#4297]
### Which OpenObserve functionalities are the source of the bug?

traces

### Is this a regression?

Yes

### Description

User report this panic:
```
thread 'actix-server worker 1' panicked at src/service/traces/mod.rs:209:70:
called `Result::unwrap()` on an `Err` value: FromUtf8Error { bytes: [113, 59, 38, 88, 4, 149, 15, 86], error: Utf8Error { valid_up_to: 5, error_len: Some(1) } }
thread 'actix-server worker 0' panicked at src/service/traces/mod.rs:209:70:
called `Result::unwrap()` on an `Err` value: FromUtf8Error { bytes: [113, 59, 38, 88, 4, 149, 15, 86], error: Utf8Error { valid_up_to: 5, error_len: Some(1) } }
```

And the sample data:
```
{
  "resource": {
    "dropped_attributes_count": 0,
    "attributes": {
      "service.name": "frontendproxy",
      "service.namespace": "default",
      "k8s.pod.ip": "10.244.1.125",
      "k8s.pod.start_time": "2024-06-17T10:11:05Z",
      "k8s.pod.uid": "71768770-5855-4b37-8dca-d1f083c34673",
      "k8s.deployment.name": "my-otel-demo-frontendproxy",
      "k8s.node.name": "minikube",
      "k8s.pod.name": "my-otel-demo-frontendproxy-f8ccc6d56-4lwv2",
      "k8s.namespace.name": "default",
      "service.instance.id": "71768770-5855-4b37-8dca-d1f083c34673",
      "host.name": "my-otel-demo-otelcol-5699cd46bf-7bdcx",
      "os.type": "linux"
    }
  },
  "instrumentation_library_spans": [
    {
      "instrumentation_library": {
        "name": "unknown",
        "version": "unknown"
      },
      "spans": [
        {
          "trace_id": "896caccfacc70215aef6bacc277eb81d",
          "span_id": "76539ec73ee392f2",
          "trace_state": "",
          "parent_span_id": "ff0830e83a47677f",
          "name": "router frontend egress",
          "kind": 3,
          "start_time_unix_nano": 1723803194462060000,
          "end_time_unix_nano": 1723803194496959000,
          "attributes": {
            "http.protocol": "HTTP/1.1",
            "upstream_address": "10.99.88.155:8080",
            "peer.address": "10.99.88.155:8080",
            "component": "proxy",
            "upstream_cluster": "frontend",
            "upstream_cluster.name": "frontend",
            "http.status_code": "200",
            "response_flags": "-"
          },
          "dropped_attributes_count": 0,
          "events": [],
          "dropped_events_count": 0,
          "links": [],
          "dropped_links_count": 0,
          "status": {
            "code": 0,
            "message": ""
          }
        },
        {
          "trace_id": "896caccfacc70215aef6bacc277eb81d",
          "span_id": "ff0830e83a47677f",
          "trace_state": "",
          "parent_span_id": "",
          "name": "ingress",
          "kind": 2,
          "start_time_unix_nano": 1723803194461942000,
          "end_time_unix_nano": 1723803194496981000,
          "attributes": {
            "node_id": "",
            "zone": "",
            "guid:x-request-id": "0bb057d8-7e50-9615-803c-ee70280da195",
            "http.url": "http://my-otel-demo-frontendproxy:8080/images/products/EclipsmartTravelRefractorTelescope.jpg",
            "http.method": "GET",
            "downstream_cluster": "-",
            "user_agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/120.0.6099.28 Safari/537.36",
            "http.protocol": "HTTP/1.1",
            "peer.address": "10.244.1.127",
            "request_size": "0",
            "response_size": "543693",
            "component": "proxy",
            "upstream_cluster": "frontend",
            "upstream_cluster.name": "frontend",
            "http.status_code": "200",
            "response_flags": "-"
          },
          "dropped_attributes_count": 0,
          "events": [],
          "dropped_events_count": 0,
          "links": [],
          "dropped_links_count": 0,
          "status": {
            "code": 0,
            "message": ""
          }
        },
        {
          "trace_id": "be4c0171269621c4d48e55b2f8768020",
          "span_id": "44214a680f2eaa9c",
          "trace_state": "",
          "parent_span_id": "4dce0f5aaeb886e7",
          "name": "router frontend egress",
          "kind": 3,
          "start_time_unix_nano": 1723803179720239000,
          "end_time_unix_nano": 1723803194719174000,
          "attributes": {
            "canceled": "true",
            "http.protocol": "HTTP/1.1",
            "upstream_address": "10.99.88.155:8080",
            "peer.address": "10.99.88.155:8080",
            "component": "proxy",
            "upstream_cluster": "frontend",
            "upstream_cluster.name": "frontend",
            "http.status_code": "0",
            "response_flags": "-",
            "error": "true"
          },
          "dropped_attributes_count": 0,
          "events": [],
          "dropped_events_count": 0,
          "links": [],
          "dropped_links_count": 0,
          "status": {
            "code": 0,
            "message": ""
          }
        },
        {
          "trace_id": "be4c0171269621c4d48e55b2f8768020",
          "span_id": "4dce0f5aaeb886e7",
          "trace_state": "",
          "parent_span_id": "b6f8cc597572241a",
          "name": "ingress",
          "kind": 2,
          "start_time_unix_nano": 1723803179720154000,
          "end_time_unix_nano": 1723803194719314000,
          "attributes": {
            "node_id": "",
            "zone": "",
            "guid:x-request-id": "d4b12b9a-a337-9e94-b9e3-801df2c98dea",
            "http.url": "http://my-otel-demo-frontendproxy:8080/api/checkout",
            "http.method": "POST",
            "downstream_cluster": "-",
            "user_agent": "python-requests/2.31.0",
            "http.protocol": "HTTP/1.1",
            "peer.address": "10.244.1.127",
            "request_size": "386",
            "response_size": "24",
            "component": "proxy",
            "upstream_cluster": "frontend",
            "upstream_cluster.name": "frontend",
            "http.status_code": "504",
            "response_flags": "UT",
            "error": "true"
          },
          "dropped_attributes_count": 0,
          "events": [],
          "dropped_events_count": 0,
          "links": [],
          "dropped_links_count": 0,
          "status": {
            "code": 0,
            "message": ""
          }
        },
        {
          "trace_id": "901cd05de5fc37f74023de7b1a26cc4f",
          "span_id": "0560644a2bc1ceda",
          "trace_state": "",
          "parent_span_id": "f5940556409b730f",
          "name": "router frontend egress",
          "kind": 3,
          "start_time_unix_nano": 1723803195213902000,
          "end_time_unix_nano": 1723803195216276000,
          "attributes": {
            "http.protocol": "HTTP/1.1",
            "upstream_address": "10.99.88.155:8080",
            "peer.address": "10.99.88.155:8080",
            "component": "proxy",
            "upstream_cluster": "frontend",
            "upstream_cluster.name": "frontend",
            "http.status_code": "500",
            "response_flags": "-",
            "error": "true"
          },
          "dropped_attributes_count": 0,
          "events": [],
          "dropped_events_count": 0,
          "links": [],
          "dropped_links_count": 0,
          "status": {
            "code": 0,
            "message": ""
          }
        }
      ],
      "schema_url": ""
    }
  ],
  "schema_url": "https://opentelemetry.io/schemas/1.6.1",
  "_time": 1723804064.502,
  "cribl_pipe": "passthru"
}
```

**Comment by c0va23** [comment]
I faced the same issue yesterday after updating openobserve from 0.10.6 to 0.10.9. My theory is that this issue caused by  [types of span_id and trace_id](https://github.com/openobserve/openobserve/blob/0b966383ef820a0a23ecf696d9c37990455bbd66/src/common/meta/traces.rs#L68-L69) fields on SpanLinkContext struct. I think it should be SpanId and TraceId, and related functions should be used to parse values.

**Comment by hengfeiyang** [comment]
@c0va23, thanks, can you share some example data?

**Comment by hengfeiyang** [comment]
I found the issue. will fix soon.

**Comment by hengfeiyang** [comment]
fixed
