### ISSUE TITLE
getting a panic on rather simple prom query

### ISSUE THREAD

**Issue by soanni86** [openobserve/openobserve#5152]
### Which OpenObserve functionalities are the source of the bug?

metrics

### Is this a regression?

Yes

### Description

hello, while trying to run the simple query

`topk(5, count by (__name__)({env="dev"}))`

getting the response

```
{
  "status": "error",
  "errorType": "bad_data",
  "error": "search node error"
}
```

the querier logs show this

```
2024-11-26T05:51:47.469685835+00:00 ERROR openobserve::service::promql::search: promql->search->grpc: node: http://240.4.51.19:5081, search err: Status { code: Cancelled, message: "h2 protocol error: http2 error", source: Some(tonic::transport::Error(Transport, hyper::Error(Http2, Error { kind: Reset(StreamId(17), CANCEL, Remote) }))) }

DEBUG h2::codec::framed_write: send frame=Headers { stream_id: StreamId(25), flags: (0x4: END_HEADERS) },
thread 'grpc_runtime' panicked at src/service/promql/engine.rs:329:18:,
```
Please advise what could be wrong

### Please provide the exception or error you saw

```true
2024-11-26T05:51:47.469685835+00:00 ERROR openobserve::service::promql::search: promql->search->grpc: node: http://240.4.51.19:5081, search err: Status { code: Cancelled, message: "h2 protocol error: http2 error", source: Some(tonic::transport::Error(Transport, hyper::Error(Http2, Error { kind: Reset(StreamId(17), CANCEL, Remote) }))) }

DEBUG h2::codec::framed_write: send frame=Headers { stream_id: StreamId(25), flags: (0x4: END_HEADERS) },
thread 'grpc_runtime' panicked at src/service/promql/engine.rs:329:18:,
```

### Please provide the version you discovered this bug in (check about page for version information)

```true
$ ./openobserve -V
openobserve v0.13.1

openobserve is deployed in HA mode using the helm-chart https://github.com/openobserve/openobserve-helm-chart/tree/main/charts/openobserve
```

**Comment by prabhatsharma** [comment]
Are you getting panic only on promql query or SQL queries too?

**Comment by hengfeiyang** [comment]
```
topk(5, count by (__name__)({env="dev"}))
```
need to set a stream name(metrics name), for example:

```
topk(5, count by (__name__)(zo_ingest_bytes{env="dev"}))
```
or
```
topk(5, count by (__name__)({__name=~"metric name", env="dev"}))
```

**Comment by soanni86** [comment]
@prabhatsharma this is the only query im getting panic

**Comment by soanni86** [comment]
@hengfeiyang on victoria metrics this kind of query works fine, idea is to identify top 5 time series across all (and this is a good "performance" test when you have terrabytes of metrics data). is this kind of query not supported on openobserve due to some implementation limitations like every metric being a separate stream ?

**Comment by hengfeiyang** [comment]
Yes, we have some limitations that each query must have metrics name or have a fitler `{__name__~="regex pattern"}`
