### ISSUE TITLE
 error accepting connection: No file descriptors available (os error 24)

### ISSUE THREAD

**Issue by chiikin** [openobserve/openobserve#862]
### Which OpenObserve functionalities are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

I use filebeat to collect logs and telegraf to collect metrics.84 streams in total. First-time run can last for 5 hours.Afterwards, it will give an error and restarting it doesn’t work properly either。
I found that the program outputted the error message -  error accepting connection: No file descriptors available (os error 24).

### Please provide the exception or error you saw

```true
[2023-06-01T06:05:39Z ERROR actix_server::accept] error accepting connection: No file descriptors available (os error 24)
[2023-06-01T06:05:39Z INFO  actix_web::middleware::logger] 192.168.122.7 "GET /api/default/ HTTP/1.1" 200 221 "-" "-" "Elastic-filebeat/8.7.0 (windows; amd64; unknown; 0001-01-01 00:00:00 +0000 UTC)" 0.001691
[2023-06-01T06:05:39Z INFO  actix_web::middleware::logger] 192.168.122.7 "GET /api/default/_license?human=false HTTP/1.1" 200 39 "-" "-" "Elastic-filebeat/8.7.0 (windows; amd64; unknown; 0001-01-01 00:00:00 +0000 UTC)" 0.000541
[2023-06-01T06:05:39Z INFO  actix_web::middleware::logger] 192.168.122.7 "HEAD /api/default/_index_template/logs HTTP/1.1" 200 269 "-" "-" "Elastic-filebeat/8.7.0 (windows; amd64; unknown; 0001-01-01 00:00:00 +0000 UTC)" 0.000312
[2023-06-01T06:05:39Z INFO  actix_web::middleware::logger] 192.168.122.7 "PUT /api/default/_index_template/logs HTTP/1.1" 200 48 "97887" "-" "Elastic-filebeat/8.7.0 (windows; amd64; unknown; 0001-01-01 00:00:00 +0000 UTC)" 0.001203
[2023-06-01T06:05:39Z INFO  actix_web::middleware::logger] 192.168.122.7 "GET /api/default/_data_stream/logs HTTP/1.1" 200 76 "-" "-" "Elastic-filebeat/8.7.0 (windows; amd64; unknown; 0001-01-01 00:00:00 +0000 UTC)" 0.000499
[2023-06-01T06:05:39Z INFO  actix_web::middleware::logger] 192.168.122.7 "GET /api/default/ HTTP/1.1" 200 221 "-" "-" "Elastic-filebeat/8.7.0 (windows; amd64; unknown; 0001-01-01 00:00:00 +0000 UTC)" 0.001482
thread 'actix-server worker 2' panicked at 'open wal file [./data/openobserve/wal/files/default/logs/sitelogs/0_2023_06_01_02_.timestamp=1685586606125000_7069916892412116992.json] error: No file descriptors available (os error 24)', src/infra/file_lock.rs:246:37
[2023-06-01T06:05:40Z ERROR actix_server::accept] error accepting connection: No file descriptors available (os error 24)
thread 'actix-server worker 3' panicked at 'open wal file [./data/openobserve/wal/files/default/metrics/mem_used_percent/0_2023_06_01_06_7069916893808820224.json] error: No file descriptors available (os error 24)', src/infra/file_lock.rs:246:37
[2023-06-01T06:05:40Z ERROR actix_server::accept] error accepting connection: No file descriptors available (os error 24)
[2023-06-01T06:05:40Z INFO  actix_web::middleware::logger] 192.168.122.7 "GET /api/default/ HTTP/1.1" 200 221 "-" "-" "Elastic-filebeat/8.7.0 (windows; amd64; unknown; 0001-01-01 00:00:00 +0000 UTC)" 0.001869
[2023-06-01T06:05:40Z INFO  actix_web::middleware::logger] 192.168.122.7 "GET /api/default/_license?human=false HTTP/1.1" 200 39 "-" "-" "Elastic-filebeat/8.7.0 (windows; amd64; unknown; 0001-01-01 00:00:00 +0000 UTC)" 0.000639
[2023-06-01T06:05:40Z INFO  actix_web::middleware::logger] 192.168.122.7 "HEAD /api/default/_index_template/logs HTTP/1.1" 200 269 "-" "-" "Elastic-filebeat/8.7.0 (windows; amd64; unknown; 0001-01-01 00:00:00 +0000 UTC)" 0.000265
[2023-06-01T06:05:41Z INFO  actix_web::middleware::logger] 192.168.122.7 "PUT /api/default/_index_template/logs HTTP/1.1" 200 48 "97887" "-" "Elastic-filebeat/8.7.0 (windows; amd64; unknown; 0001-01-01 00:00:00 +0000 UTC)" 0.000822
[2023-06-01T06:05:41Z INFO  actix_web::middleware::logger] 192.168.122.7 "GET /api/default/_data_stream/logs HTTP/1.1" 200 76 "-" "-" "Elastic-filebeat/8.7.0 (windows; amd64; unknown; 0001-01-01 00:00:00 +0000 UTC)" 0.000555
[2023-06-01T06:05:41Z INFO  actix_web::middleware::logger] 192.168.122.7 "GET /api/default/ HTTP/1.1" 200 221 "-" "-" "Elastic-filebeat/8.7.0 (windows; amd64; unknown; 0001-01-01 00:00:00 +0000 UTC)" 0.001534
thread 'actix-server worker 4' panicked at 'open wal file [./data/openobserve/wal/files/default/logs/sitelogs/0_2023_06_01_02_.timestamp=1685586613126000_7069916898162507777.json] error: No file descriptors available (os error 24)', src/infra/file_lock.rs:246:37
[2023-06-01T06:05:43Z ERROR actix_server::accept] error accepting connection: No file descriptors available (os error 24)
[2023-06-01T06:05:43Z INFO  actix_web::middleware::logger] 192.168.122.7 "GET /api/default/ HTTP/1.1" 200 221 "-" "-" "Elastic-filebeat/8.7.0 (windows; amd64; unknown; 0001-01-01 00:00:00 +0000 UTC)" 0.001847
[2023-06-01T06:05:43Z INFO  actix_web::middleware::logger] 192.168.122.7 "GET /api/default/_license?human=false HTTP/1.1" 200 39 "-" "-" "Elastic-filebeat/8.7.0 (windows; amd64; unknown; 0001-01-01 00:00:00 +0000 UTC)" 0.000526
[2023-06-01T06:05:43Z INFO  actix_web::middleware::logger] 192.168.122.7 "HEAD /api/default/_index_template/logs HTTP/1.1" 200 269 "-" "-" "Elastic-filebeat/8.7.0 (windows; amd64; unknown; 0001-01-01 00:00:00 +0000 UTC)" 0.000235
[2023-06-01T06:05:43Z INFO  actix_web::middleware::logger] 192.168.122.7 "PUT /api/default/_index_template/logs HTTP/1.1" 200 48 "97887" "-" "Elastic-filebeat/8.7.0 (windows; amd64; unknown; 0001-01-01 00:00:00 +0000 UTC)" 0.000877
[2023-06-01T06:05:43Z INFO  actix_web::middleware::logger] 192.168.122.7 "GET /api/default/_data_stream/logs HTTP/1.1" 200 76 "-" "-" "Elastic-filebeat/8.7.0 (windows; amd64; unknown; 0001-01-01 00:00:00 +0000 UTC)" 0.000578
[2023-06-01T06:05:43Z INFO  actix_web::middleware::logger] 192.168.122.7 "GET /api/default/ HTTP/1.1" 200 221 "-" "-" "Elastic-filebeat/8.7.0 (windows; amd64; unknown; 0001-01-01 00:00:00 +0000 UTC)" 0.001717
thread 'actix-server worker 5' panicked at 'open wal file [./data/openobserve/wal/files/default/logs/sitelogs/0_2023_06_01_02_.timestamp=1685586607917000_7069916908065259520.json] error: No file descriptors available (os error 24)', src/infra/file_lock.rs:246:37
[2023-06-01T06:05:44Z ERROR actix_server::accept] error accepting connection: No file descriptors available (os error 24)
[2023-06-01T06:05:44Z INFO  actix_web::middleware::logger] 192.168.122.7 "GET /api/default/ HTTP/1.1" 200 221 "-" "-" "Elastic-filebeat/8.7.0 (windows; amd64; unknown; 0001-01-01 00:00:00 +0000 UTC)" 0.001669
[2023-06-01T06:05:44Z INFO  actix_web::middleware::logger] 192.168.122.7 "GET /api/default/_license?human=false HTTP/1.1" 200 39 "-" "-" "Elastic-filebeat/8.7.0 (windows; amd64; unknown; 0001-01-01 00:00:00 +0000 UTC)" 0.000510
[2023-06-01T06:05:44Z INFO  actix_web::middleware::logger] 192.168.122.7 "HEAD /api/default/_index_template/logs HTTP/1.1" 200 269 "-" "-" "Elastic-filebeat/8.7.0 (windows; amd64; unknown; 0001-01-01 00:00:00 +0000 UTC)" 0.000219
[2023-06-01T06:05:45Z INFO  actix_web::middleware::logger] 192.168.122.7 "PUT /api/default/_index_template/logs HTTP/1.1" 200 48 "97887" "-" "Elastic-filebeat/8.7.0 (windows; amd64; unknown; 0001-01-01 00:00:00 +0000 UTC)" 0.001370
[2023-06-01T06:05:45Z INFO  actix_web::middleware::logger] 192.168.122.7 "GET /api/default/_data_stream/logs HTTP/1.1" 200 76 "-" "-" "Elastic-filebeat/8.7.0 (windows; amd64; unknown; 0001-01-01 00:00:00 +0000 UTC)" 0.000568
[2023-06-01T06:05:45Z INFO  actix_web::middleware::logger] 192.168.122.7 "GET /api/default/ HTTP/1.1" 200 221 "-" "-" "Elastic-filebeat/8.7.0 (windows; amd64; unknown; 0001-01-01 00:00:00 +0000 UTC)" 0.001623
thread 'actix-server worker 6' panicked at 'open wal file [./data/openobserve/wal/files/default/logs/sitelogs/0_2023_06_01_02_.timestamp=1685586624117000_7069916915099107328.json] error: No file descriptors available (os error 24)', src/infra/file_lock.rs:246:37
[2023-06-01T06:05:46Z ERROR actix_server::accept] error accepting connection: No file descriptors available (os error 24)
[2023-06-01T06:05:46Z INFO  actix_web::middleware::logger] 192.168.122.7 "GET /api/default/ HTTP/1.1" 200 221 "-" "-" "Elastic-filebeat/8.7.0 (windows; amd64; unknown; 0001-01-01 00:00:00 +0000 UTC)" 0.001876
[2023-06-01T06:05:46Z INFO  actix_web::middleware::logger] 192.168.122.7 "GET /api/default/_license?human=false HTTP/1.1" 200 39 "-" "-" "Elastic-filebeat/8.7.0 (windows; amd64; unknown; 0001-01-01 00:00:00 +0000 UTC)" 0.000498
[2023-06-01T06:05:46Z INFO  actix_web::middleware::logger] 192.168.122.7 "HEAD /api/default/_index_template/logs HTTP/1.1" 200 269 "-" "-" "Elastic-filebeat/8.7.0 (windows; amd64; unknown; 0001-01-01 00:00:00 +0000 UTC)" 0.000277
[2023-06-01T06:05:46Z INFO  actix_web::middleware::logger] 192.168.122.7 "PUT /api/default/_index_template/logs HTTP/1.1" 200 48 "97887" "-" "Elastic-filebeat/8.7.0 (windows; amd64; unknown; 0001-01-01 00:00:00 +0000 UTC)" 0.000867
[2023-06-01T06:05:46Z INFO  actix_web::middleware::logger] 192.168.122.7 "GET /api/default/_data_stream/logs HTTP/1.1" 200 76 "-" "-" "Elastic-filebeat/8.7.0 (windows; amd64; unknown; 0001-01-01 00:00:00 +0000 UTC)" 0.000579
[2023-06-01T06:05:46Z INFO  actix_web::middleware::logger] 192.168.122.7 "GET /api/default/ HTTP/1.1" 200 221 "-" "-" "Elastic-filebeat/8.7.0 (windows; amd64; unknown; 0001-01-01 00:00:00 +0000 UTC)" 0.001602
thread 'actix-server worker 7' panicked at 'open wal file [./data/openobserve/wal/files/default/logs/sitelogs/0_2023_06_01_02_.timestamp=1685586615893000_7069916921390563328.json] error: No file descriptors available (os error 24)', src/infra/file_lock.rs:246:37
[2023-06-01T06:05:47Z ERROR actix_server::accept] error accepting connection: No file descriptors available (os error 24)
[2023-06-01T06:05:47Z INFO  actix_web::middleware::logger] 192.168.122.7 "GET /api/default/ HTTP/1.1" 200 221 "-" "-" "Elastic-filebeat/8.7.0 (windows; amd64; unknown; 0001-01-01 00:00:00 +0000 UTC)" 0.001840
[2023-06-01T06:05:47Z INFO  actix_web::middleware::logger] 192.168.122.7 "GET /api/default/_license?human=false HTTP/1.1" 200 39 "-" "-" "Elastic-filebeat/8.7.0 (windows; amd64; unknown; 0001-01-01 00:00:00 +0000 UTC)" 0.000520
[2023-06-01T06:05:47Z INFO  actix_web::middleware::logger] 192.168.122.7 "GET /api/default/ HTTP/1.1" 200 221 "-" "-" "Elastic-filebeat/8.7.0 (windows; amd64; unknown; 0001-01-01 00:00:00 +0000 UTC)" 0.001507
[2023-06-01T06:05:47Z INFO  actix_web::middleware::logger] 192.168.122.7 "HEAD /api/default/_index_template/logs HTTP/1.1" 200 269 "-" "-" "Elastic-filebeat/8.7.0 (windows; amd64; unknown; 0001-01-01 00:00:00 +0000 UTC)" 0.000223
[2023-06-01T06:05:48Z INFO  actix_web::middleware::logger] 192.168.122.7 "PUT /api/default/_index_template/logs HTTP/1.1" 200 48 "97887" "-" "Elastic-filebeat/8.7.0 (windows; amd64; unknown; 0001-01-01 00:00:00 +0000 UTC)" 0.001343
[2023-06-01T06:05:48Z INFO  actix_web::middleware::logger] 192.168.122.7 "GET /api/default/_data_stream/logs HTTP/1.1" 200 76 "-" "-" "Elastic-filebeat/8.7.0 (windows; amd64; unknown; 0001-01-01 00:00:00 +0000 UTC)" 0.000524
thread 'actix-server worker 0' panicked at 'open wal file [./data/openobserve/wal/files/default/logs/sitelogs/0_2023_06_01_02_.timestamp=1685586613126000_7069916927799459840.json] error: No file descriptors available (os error 24)', src/infra/file_lock.rs:246:37
```

### Please provide the version you discovered this bug in (check about page for version information)

```true
OS: centos7
version:  openobserve-v0.4.6-linux-amd64-musl.tar.gz
```

### Anything else?

lsof -n |awk '{print $2}'|sort|uniq -c |sort -nr|more
fd count: 106559
ulimit -n 
4096

streams: 84

**Comment by prabhatsharma** [comment]
With just 84 streams you should not run out of file descriptors unless there are other processes grabbing many available file descriptors (there could be a bug in openobserve too). Let's debug it together.

Can you try increasing the ulimit  to say 8192 by using below command and let us know if that solves:

```shell
ulimit -n 8192
```

**Comment by chiikin** [comment]
I’m running OpenObserve on a test server, which also has ZincSearch, n9e, redis, NetData, MySQL and VictoriaMetrics running in it.

I ran the `ulimit -n 8192` command, and now OpenObserve looks good. I’ll observe it for a while first.
